require(ggplot2)
diamond<-data("diamonds")
ggplot(data = diamonds)
rm(diamond)
ggplot(data = diamonds)+ geom_histogram(aes(x = carat))
ggplot(data = diamonds)+ geom_histogram(aes(x = carat),binwidth = 0.35)
ggplot(data = diamonds)+ geom_histogram(aes(x = carat),binwidth = 0.12)
ggplot(data=diamonds)+ geom_density(aes(x = carat),fill="grey50")
gg<- ggplot(data = diamonds, aes(x = carat,y = price ))
head(diamonds)
gg+geom_point()
gg+geom_point(aes(colour=color))
gg+geom_point(aes(colour=color,cut=cut))
gg+geom_point(aes(colour=color,shape=cut))+geom_jitter()
